# Generated by Django 4.2.6 on 2023-10-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='team',
            new_name='teams',
        ),
    ]
