# Generated by Django 4.2.6 on 2023-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_rename_team_tournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_round_schedule_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
    ]
