# Generated by Django 4.2.6 on 2023-10-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_coach_user_alter_manager_user_alter_team_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiter_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiter_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournamet_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.AddField(
            model_name='regiter_team',
            name='tournament_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamet_register'),
        ),
    ]
