# Generated by Django 4.2.6 on 2023-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_regiter_team_tournamet_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiter_team',
            name='regiter_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
