# Generated by Django 4.2.6 on 2023-10-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_remove_schedule_team_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='regiter_date',
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamet_register'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.regiter_team'),
        ),
    ]
