# Generated by Django 4.2.6 on 2023-10-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_remove_schedule_regiter_date_alter_match_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamet_register'),
        ),
    ]
