# Generated by Django 4.2.6 on 2023-10-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_match_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='confomed_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiter_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.regiter_team')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='tournament.confomed_team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='tournament.confomed_team'),
        ),
    ]
