# Generated by Django 4.2.6 on 2023-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_schedule_started_time_schedule_tournament_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
