# Generated by Django 4.2.6 on 2023-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_match_score_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('ended', 'Ended')], max_length=10),
        ),
    ]
