# Generated by Django 4.2.6 on 2023-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('soon', 'soon'), ('started', 'Started'), ('ended', 'Ended')], max_length=10),
        ),
    ]
